### ISSUE TITLE
New plugin gives error when enabled

### ISSUE THREAD

**Issue by xorl** [cloudtruth/argocd-cloudtruth-plugin#7]
When the plugin is selected the config throws an error:

`rpc error: code = Unknown desc = plugin sidecar failed. couldn't find cmp-server plugin with name argocd-cloudtruth-plugin-v0.7.0 supporting the given repository`

**Comment by wr0ngway** [comment]
This is a drawback to the new plugin scheme that argocd implemented.  They have a divergent setup path when one is using a sidecar plugin. One can either choose to use a gitops style enablement by having the plugin look for a file in the repo, or continue to require enablement through the cli or webui, but one can't do both.  You _can_ manually craft the Application manifest to enable the plugin, just can't use the usual cli/webui method.  We chose to go with the gitops style enablement.  To enable a project to use the plugin, create the file `.argocd-cloudtruth-plugin` in the root of the repository or the directory of your argo project if you qualify the repo with a path.  This file can be blank or can be a yaml file with customizations for the plugin parameters (e.g. set `cloudtruth-project`).  More details [here](https://github.com/cloudtruth/argocd-cloudtruth-plugin#usage) - note the link to the argo docs describing how to manually craft the Application manifest if thats what you prefer.

Let me know if this fixes your problem.  Also, now that you know more about the possible mechanisms, do you agree with our choice to go with gitops style enablement?

**Comment by xorl** [comment]
Awesome, that works for me, thank you!
